/* Build assets/css/icons.css from the Phosphor SVGs the site actually uses,
   plus the lab's own marks.

   Delivery is CSS mask rather than an icon font or an inline <use> sprite,
   because it is the only option that needs zero markup changes: every
   `<i class="ph ph-cpu">` already on the page keeps working, keeps taking its
   colour from currentColor and its size from font-size. The font it replaces
   shipped all 9000 glyphs to render the 105 this site asks for. */
const fs = require('fs');
const path = require('path');

const SRC = process.argv[2];          // folder of downloaded phosphor svgs
const REPO = process.argv[3];
const OUT = path.join(REPO, 'assets/css/icons.css');

// The lab's own marks, mapped to the class a page would use for them.
const OWN = {
  // Only monochrome marks belong here. A mask throws away colour, so the
  // chameleon eye, the aurora and the HITS emblem would come out as flat
  // silhouettes; those stay <img> elements and keep their own palette.
  'nips-atom': 'assets/icons/atom.svg',
  'nips-yanc': 'assets/icons/yanc.svg',
  'nips-mark': 'assets/icons/icon_home_nipscern.svg',
};

/* A mask only needs the silhouette, so colour attributes are dead weight and
   would be ignored anyway. Strip them, collapse whitespace, then percent-encode
   the few characters that cannot sit raw inside a url("...") in CSS. */
function clean(svg) {
  return svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s(fill|stroke)="(?!none)[^"]*"/g, '')
    .replace(/\s(width|height)="[^"]*"/g, '')
    .replace(/>\s+</g, '><')
    .replace(/\s{2,}/g, ' ')
    .trim();
}

function dataUri(svg) {
  return "url(\"data:image/svg+xml," + clean(svg)
    .replace(/"/g, "'")
    .replace(/#/g, '%23')
    .replace(/</g, '%3C')
    .replace(/>/g, '%3E')
    .replace(/\{/g, '%7B')
    .replace(/\}/g, '%7D') + "\")";
}

const rules = [];
let n = 0, own = 0;

for (const f of fs.readdirSync(SRC).filter(f => f.endsWith('.svg')).sort()) {
  const name = path.basename(f, '.svg');
  rules.push(`.ph-${name}{--ph:${dataUri(fs.readFileSync(path.join(SRC, f), 'utf8'))}}`);
  n++;
}
for (const [name, rel] of Object.entries(OWN)) {
  const p = path.join(REPO, rel);
  if (!fs.existsSync(p)) { console.log(`  faltando: ${rel}`); continue; }
  rules.push(`.ph-${name}{--ph:${dataUri(fs.readFileSync(p, 'utf8'))}}`);
  own++;
}

const header = `/* ============================================================
   Icons — self-hosted, no third-party origin
   ------------------------------------------------------------
   Generated by tools/build-icons.js. Do not edit by hand.

   Replaces the Phosphor icon webfont, which cost 147 KB of woff2 plus 12 KB of
   CSS on every page to draw the ${n} glyphs this site actually uses. Each icon
   here is a CSS mask over currentColor, so the existing markup is untouched:
   an <i class="ph ph-cpu"> still takes its colour from the surrounding text and
   its size from font-size, exactly as it did with the font.

   The lab's own marks are in the same file under .ph-nips-*, so a project's
   real emblem can stand where a generic glyph used to.

   Phosphor Icons is MIT licensed. See credits.html.
   ============================================================ */
.ph{display:inline-block;width:1em;height:1em;flex-shrink:0;background-color:currentColor;-webkit-mask:var(--ph) no-repeat center;mask:var(--ph) no-repeat center;-webkit-mask-size:contain;mask-size:contain;vertical-align:-0.125em}
`;

fs.writeFileSync(OUT, (header + rules.join('\n') + '\n').replace(/\n/g, '\r\n'));

const raw = fs.statSync(OUT).size;
const gz = require('zlib').gzipSync(fs.readFileSync(OUT), { level: 9 }).length;
console.log(`  ${n} icones Phosphor + ${own} marcas proprias`);
console.log(`  ${OUT}: ${Math.round(raw / 1024)} KB cru, ${Math.round(gz / 1024)} KB gzip`);
console.log(`  fonte que sai: 147 KB woff2 + 12 KB css = 159 KB`);
